### ISSUE TITLE
Submissions "With no associated jobs" bug

### ISSUE THREAD

**Issue by Natalieflp** [OpenFn/docs#74] opened 2016-11-01 07:03 UTC
3 pages of submissions in my inbox in the past couple of days are coming in "with no associated jobs", however, nothing is different about these submissions compared to others that are intermittently coming in and processing normally. Half of the submissions listed in these pages, have actually gone through to Salesforce, while half have not. Please see the screenshot for how this is looking in the inbox.
![openfn error no job](https://cloud.githubusercontent.com/assets/17291053/19881869/589e4e94-a02f-11e6-8c39-ca00201c7e70.png)
 Can you please look into why this is happening?

**Comment by taylordowns2000** [comment] 2016-11-01 07:31
Absolutely. We're on it right now.

**Comment by taylordowns2000** [comment] 2016-11-01 08:31
Hi @Natalieflp , we've been unable to reproduce your issue so far, but I've ramped up the logging on openfn.org and am monitoring it continuously. I hope to have an update shortly!

**Comment by taylordowns2000** [comment] 2016-11-01 13:33
Hi @Natalieflp , this has been identified as an issue with our jobs queue and we've tested and pushed a fix. Thank you so much for identifying the bug!

**Closed by taylordowns2000** 2016-11-01 13:33 UTC
Labels: bug
