### ISSUE TITLE
Duplicates Don't Appear to Be Duplicates

### ISSUE THREAD

**Issue by Natalieflp** [OpenFn/docs#69] opened 2016-09-10 02:59 UTC
I have quite a few submissions coming in that are throwing a duplicate error in Salesforce, however when viewed in OpenFn they appear to be the only run for that submission. Is there a reason why they were not linked with their apparent initial run? 

What usually occurs in this situation is that there is a successful run first listed, when I click into the run in the Inbox, and then there is a subsequent failed run that shows the duplicate error. In this situation the run with the duplicate error is alone.  The data has successfully reached its destination, but it causes the filter in the inbox to inaccurately display many "with jobs in a failed state" runs, when in fact they are not failed. Please see the attached screenshots. 

<img width="1272" alt="screen shot 2016-09-09 at 7 15 57 pm" src="https://cloud.githubusercontent.com/assets/17291053/18407510/54b217e8-76c7-11e6-90e3-36e6bb59ca7a.png">
<img width="1265" alt="screen shot 2016-09-09 at 7 16 06 pm" src="https://cloud.githubusercontent.com/assets/17291053/18407511/59e055cc-76c7-11e6-83ed-14fb92a99bfc.png">

**Comment by taylordowns2000** [comment] 2016-09-10 13:52
Hi Natalie,

It appears that your data source (ODK Aggregate?) is sending multiple copies of the same "submission". It's been reported by other users as an issue with certain ODK Aggregate publishers, but the good news is that by enforcing uniqueness on the `*meta-instance-id*` field, you can ensure that duplicates don't get into your destination system.

In the case you have shown in your email, message `80820` is a duplicate of message `80817`, which was sent by ODK and successfully processed by OpenFn one second before `80820`.

https://www.openfn.org/projects/YOUR_PROJECT_UUID_GOES_HERE/receipts/80817/inspect

Thank you for posting! I'm closing this issue as OpenFn is behaving as expected, given a data source that sends multiple copies of the same message and a destination that rejects duplicates.

**Closed by taylordowns2000** 2016-09-10 13:52 UTC
Labels: bug
